@hostname = https://localhost
@port = 7227
@token = CfDJ8DfAeHPaQd1PvpvdU91NUDEv24Gb-t3lD92poZSVqa7r4KtSjtqHw-5-5MOtRZG-RxCNPEHWAYFP8-1WNpdEnnrJfxRJn9HFlJ3AdA7WUJUhPsJXNV37HIUxpi22CkcTrzTY3FkVmI-j5m2XHfkpJAt_CgyniD7wjvQANntgLAilq_64KCQI9QSVyKhB1vdlNwaFyhIU7adktMYfSLpPN12OX98Im0nyCsVyWsdc2L3b3abAeIW4WTwDIB-cVvzOtqfKkzNpMxSjiEbIXdz4pR5GBjnwT2kSwAV09Zz60cCzMx5fzR5LWNHanzwcHT9u2oqJ7La6QcYnfgH04lDxQjpns3db4GGDFXL35Kda6bxNg_aUWDtTcy2wRes2iejhTz_nPpSAAvfI18rOyIa97mz_KKWoJMURF11f9CT06-niAuVWi5kMjvzTwCumTFbm8LoxP_mdQYJNNYlYcUNb8YI7Hsxfv3xq-S427v_RvwKawIplr0oulj8pXVJMNYCwFEF_VeCG91Ucf9BoU1EXHADk8a_aLmrtvuxhABYxwGAD0CriTVNNR9wssLNmIfUU5AzQXA4pDZdFmvv0jE6BF7y8dOxRGaDX0UqKPTAV4hxNohUuty3svfvdYEgJm2T-0wpFZ84x20VqtfW4lgRRN1TYoHqbxQ4DHVTO1L1glRIW-L3WUwSiMdcE5NtmRlUu1SwCs1t2YFs-2-huhQW37LTs-O24589Go-UmJWqPtsqkzzJ19194z_3E5lWoBsr5qOI8ViIU5V-3aXGD-I8bT5PlE0O2RQKgVwZKG1H2nS9D

@Restaurants.API_HostAddress = https://localhost:7227

# ===================================
# Region: Dishes Endpoints
# ===================================

### Get All Restaurants
GET {{Restaurants.API_HostAddress}}/api/restaurants

### Get Single Restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurants/9
Authorization: Bearer {{token}}

### Create New Restaurant
POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sushi Haven",
  "description": "An elegant sushi bar with a wide variety of traditional and fusion rolls.",
  "category": "Japanese",
  "hasDelivery": true,
  "contactEmail": "orders@sushihaven.com",
  "contactNumber": "+15556543",
  "city": "Los Angeles",
  "street": "222 Sakura Blvd",
  "postalCode": "90-012"
}

### Delete Restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/8

### Update Restaurant
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/11
Content-Type: application/json

{
  "name": "Morning Bliss Cafe",
  "description": "A charming cafe serving artisanal coffee and breakfast all day.",
  "hasDelivery": false
}

###
# ===================================
# Region: Dishes Endpoints
# ===================================

### Create New Dish for Restaurant
POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
  "name": "Caesar Salad",
  "description": "Fresh romaine lettuce with Caesar dressing, croutons, and Parmesan cheese.",
  "price": 7.49,
  "kiloCalories": 300
}

### Get All Dishes for a Restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes

### Get Single Dish for a Restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes/4

### Delete Single Dish for a Restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes/3

### Delete All Dishes for a Restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes

### Update Dish for a Restaurant
PATCH {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes/3
Content-Type: application/json

{
  "name": "Spaghetti Bolognese",
  "description": "A classic Italian pasta dish with rich meat sauce.",
  "price": 15.99,
  "kiloCalories": 820
}

###
# ===================================
# Region: User Endpoints
# ===================================

### Create New User
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password1!"
}

### Login
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Password1!"
}

### Update User
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Mahmoud",
  "lastName": "Saleh",
  "dateOfBirth": "1999-12-15",
  "nationality": "Egyptian"
}

### Assign User Role
PATCH {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "userEmail": "3ZlGd@example.com",
   "roleName": "User"
}

### Unassign User Role
DELETE {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "userEmail": "3ZlGd@example.com",
   "roleName": "User"
}

###
