@hostname = https://localhost
@port = 7227
@token = CfDJ8DfAeHPaQd1PvpvdU91NUDFz5FHXUk8Dsd8m5EReuoJlMifx_uwk9AGVnVdQAd0wBgsX1-JS2PwRfiKCIMT5qCkj4AIepItmwLpaS8-4bhXn2fs6T_iEmaqewlk-hNyQoXbNwd9BZGnMErwZzP_CznGrp7gE0CMTGFtL7-alDRkRFN_lcvNHZvlhIPwzfRCIBNyxinIjptF0qZctFRnSGvh7SjX1vhaJQzczlIWrR-xOu_hVWzfaSKoBzVNTENT_goi2kmKcCd2tLLf4ODie12Wt3qGWZnO1_Bfh0QCvHvgISonJ4_ZEjfDaGQLfkmm4SsfsJFPK1jAN8rW6t21o6SOfKKQa8AbdU6GhKxxXDSznNWqkKA6jZfTzA6IIUP3EVU6I3hXTP2fkvDEbOANgUlnoj-g57UeVFAQLuP4Pk7O7sHmngVcrpq4cTKzxOMlwaz1u50MLRR9sUUr-GGrApN5US76g32P_fvhowMOH7d1XfnRRe98-QC8r8GdFDfqC4irbfZWsXi7Kvc48R0uiTM3jdCav7hio5z_RfCDAw-BBlmIu8JuJFN1YosYSkqkKn1MyBOhJEV8-IF-3afmxhXh8T9g7v8t3oWPPItDOWhvSdv9pViPyUGQ3iFC_jG0qDuqw8VT6mUFDsJe7ob_BDu6MFMW3W5LwsGyl-FjkvkWDK12S_wKn932UrPG23OjQICS8MEseIxqkbtoVpKKAEBt-U4P5Tzi9mN2ETh1ksyf_kSz52gLE4wEY9RFfa0JBIfuRJhBcu41-N6fZ_F2YrQ71BRuPuFbBazIN9IOBaOaY

@Restaurants.API_HostAddress = https://localhost:7227

# ===================================
# Region: Dishes Endpoints
# ===================================

### Get All Restaurants
GET {{Restaurants.API_HostAddress}}/api/restaurants

### Get Single Restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurants/9
Authorization: Bearer {{token}}

### Create New Restaurant
POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sushi Haven",
  "description": "An elegant sushi bar with a wide variety of traditional and fusion rolls.",
  "category": "Japanese",
  "hasDelivery": true,
  "contactEmail": "orders@sushihaven.com",
  "contactNumber": "+15556543",
  "city": "Los Angeles",
  "street": "222 Sakura Blvd",
  "postalCode": "90-012"
}

### Delete Restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/8

### Update Restaurant
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/11
Content-Type: application/json

{
  "name": "Morning Bliss Cafe",
  "description": "A charming cafe serving artisanal coffee and breakfast all day.",
  "hasDelivery": false
}

###
# ===================================
# Region: Dishes Endpoints
# ===================================

### Create New Dish for Restaurant
POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
  "name": "Caesar Salad",
  "description": "Fresh romaine lettuce with Caesar dressing, croutons, and Parmesan cheese.",
  "price": 7.49,
  "kiloCalories": 300
}

### Get All Dishes for a Restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes

### Get Single Dish for a Restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes/4

### Delete Single Dish for a Restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes/3

### Delete All Dishes for a Restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes

### Update Dish for a Restaurant
PATCH {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes/3
Content-Type: application/json

{
  "name": "Spaghetti Bolognese",
  "description": "A classic Italian pasta dish with rich meat sauce.",
  "price": 15.99,
  "kiloCalories": 820
}

###
# ===================================
# Region: User Endpoints
# ===================================

### Create New User
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password1!"
}

### Login
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@example.com",
  "password": "Password1!"
}

### Update User
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Mahmoud",
  "lastName": "Saleh",
  "dateOfBirth": "1999-12-15",
  "nationality": "Egyptian"
}

